// This file was auto-generated by ML.NET Model Builder. 

using System;
using INTS_MLNET_PROJEKTML.Model;

namespace INTS_MLNET_PROJEKTML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Id_hotel = 1F,
                Id_user = 1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");
            Console.WriteLine($"Id_hotel: {sampleData.Id_hotel}");
            Console.WriteLine($"Id_user: {sampleData.Id_user}");
            Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
