// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace INTS_MLNET_PROJEKTML.Model
{
    public class ModelInput
    {
        [ColumnName("id_hotel"), LoadColumn(0)]
        public float Id_hotel { get; set; }


        [ColumnName("rating"), LoadColumn(1)]
        public float Rating { get; set; }


        [ColumnName("id_user"), LoadColumn(2)]
        public float Id_user { get; set; }


    }
}
